Aggiornamento sezione 4.2
CodingCowboys10/kmai pull request #118
Opened 2024-01-13 22:15 UTC by AnnaNordio

All'interno del file processiOrganizzativi.tex ho modificato la sezione 4.2 (Gestione delle infrastrutture tecniche) andando a uniformare a quello che è il resto del documento (dovrebbe essere la penultima sezione del file): Quando si revisiona scrivere "Aggiornamento sezione \ref{sec:gestioinfr}."

2024-01-13 22:22 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +L'attività sia articola nel compito di definire gli obiettivi e i requisiti delle infrastrutture tecniche. Vengono istazniati i protocolli di gestione e si stabiliscono le procedure per il monitoragg
"sia articola" --> "si articola

2024-01-13 22:26 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +            \item Al termine, il membro segnala ai verificatori la necessità di esaminare il lavoro completato, trasferendo la task allo stato di "da riesaminare" (\textit{to revise});
"da riesaminare" --> "da verificare" il verbo riesaminare mi da più l'impressione di ricontrollare qualcosa di già controllato, ma lascia quello che preferisci

2024-01-13 22:31 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +In conclusione, questo processo strutturato, dall'assegnazione delle attività alla loro revisione e approvazione, offre un efficace schema di gestione, assicurando il completamento e la validazione d
Formalmente questo sarebbe il processo di una subtask, per giunta una subtask non passa per l'approvazione del responsabile ma una volta passata la verifica andrà in done, il responsabile accetta Task intere quando il loro stato è To Approve, cioè quando tutte le sue sottotask sono finite. BIsogna capire quanto in profondità si vuole andare con la spiegazione

2024-01-13 22:33 UTC, checco296 requested changes
Vedasi commenti all'interno di processiOrganizzativi sezione 4.2

2024-01-15 21:08 UTC, AnnaNordio commented
Ho effettuato le modifiche, fai particolare attenzione all'ultima cosa che mi avevi segnalato, spero sia completa

2024-01-15 21:41 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +            \item Le attività sono suddivise durante le riunioni in task specifiche, eventualmente composte da sottotask;
togli eventualmente, tutte le task hanno sottotask

2024-01-15 21:41 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +            \item Ciascun membro del gruppo si assegna autonomamente una task o sottotask, indicando lo stato di avanzamento come "in corso" (\textit{in progress});
non ci si assegna mai una task, ci si assegna solo le sottotask

2024-01-15 21:42 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +            \item Al termine, il membro segnala ai verificatori la necessità di esaminare il lavoro completato, trasferendo la task o sottotask allo stato di "da verificare" (\textit{to revise});
come prima, solo le sottotask vengono verificate

2024-01-15 21:43 UTC, checco296 commented on 2-RTB/Norme_di_progetto/processiOrganizzativi.tex
> +            \item Dopo la revisione, se l'esito è negativo, la task o sottotask torna allo stato "da completare" (\textit{to do}), e il processo riprende dal punto 3. In caso la revisione di una sott
come prima

2024-01-15 21:48 UTC, checco296 requested changes
vedi i commenti che ho inserito

2024-01-15 22:07 UTC, checco296 approved these changes
Aggiornamento sezione \ref{sec:gestioinfr}.

2024-01-15 22:09 UTC, merged