Consuntivo 6 e preventivo 7
CodingCowboys10/kmai pull request #151
Opened 2024-02-03 21:16 UTC by AnnaNordio

2024-02-03 21:18 UTC, AnnaNordio commented
Ho ricreato anche i png di alcune road map perchè non erano con lo sfondo trasparente e faceva brutto. Un'altra cosa che ho notato è che i grafici a colonne vengono molto sgranati... cosa possiamo fare?

2024-02-03 23:08 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Piano_di_progetto/consuntivo.tex
> +Analizzando le ore impiegate in questo sprint, in relazione allo stato di avanzamento del progetto, il periodo appena terminato risulta essere nel complesso positivo nonostante il calo di produttivit
sessione d'esame, va al singolare

2024-02-03 23:14 UTC, checco296 requested changes
cambiamenti richiesti nei messaggi

2024-02-04 14:19 UTC, checco296 approved these changes
Aggiornamento capitolo \ref{chap:pianificazione}, \ref{chap:preventivo} e \ref{chap:consuntivo}.

2024-02-04 18:21 UTC, merged