Cc 163 revisione adr
CodingCowboys10/kmai pull request #154
Opened 2024-02-05 11:16 UTC by Fgiacomuzzo

Cc 163 revisione adr 

Le aggiunte ai requisiti funzionali sono alla fine, controllate anche voi se vanno bene gli uc associati.
Rimossi: requisiti prestazionali;
Aggiornati: grafici uc, tabella con totale degli uc;
Creati: nuovi uc,  requisiti e tabelle finali di riepilogo;

2024-02-05 12:34 UTC, AnnaNordio commented
bisogna mettere tutti i requisiti nel tracciamento fonte-requisito, requisito-fonte

2024-02-05 21:04 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Analisi_dei_requisiti/UC19.png
questo va eliminato!

2024-02-05 21:11 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Analisi_dei_requisiti/UC3.1.PNG
questo va eliminato!

2024-02-05 21:18 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Analisi_dei_requisiti/casiuso.tex
> +    \includegraphics[width=0.8\linewidth]{UC7.png} %da modificare
immagine sbagliata, sostituire con UC8.png

2024-02-05 21:21 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Analisi_dei_requisiti/casiuso.tex
> +    \includegraphics[width=0.9\linewidth]{UC24.PNG}
immagine sbagliata cambiare con UC26.png

2024-02-05 21:22 UTC, checco296 commented on 2-RTB/Documentazione_esterna/Analisi_dei_requisiti/casiuso.tex
> +    \includegraphics[width=0.8\linewidth]{UC7.png} %da modificare
anche descrizione dell'immagine errata

2024-02-05 21:43 UTC, checco296 requested changes
RV0-1, RVZ-5 sono requisiti funzionali. I requisiti prestazionali non sono verificabili, poiché non viene riportato alcun vincolo sull'infrastruttura di esecuzione per poter raggiungere quanto riportato. Il rimanente dei requisiti prestazionali è di vincolo o funzionale. questa parte della revisione del professor Cardin non sembra essere stata trattata

2024-02-06 12:43 UTC, checco296 approved these changes
Revisione capitoli \ref{sec:requisiti}, \ref{sec:casi}.

2024-02-06 12:48 UTC, merged